config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cars do
      resources :bookings, only: [:create, :new, :index, :show, :destroy]
  end
  resources :bookings, only: [:index, :destroy] do 
    resources :reviews, only: [:create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many_attached :photos

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_manufacturer_and_model_and_year ,
    against: [ :manufacturer, :model, :year],
    using: {
      tsearch: { prefix: true }
    }

#validations
  # validates :model, presence: true
  # validates :year, presence: true
  # validates :price, presence: true, numericality: true
  # validates :manufacturer, presence: true

  #  def initialize(attrs)
  #    require 'open-uri'
  #    photo = attrs.delete(:photo) if attrs
  #    super
  #    self.photo.attach(io: open(photo), filename: 'x') if photo
  # end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cars
  has_many :bookings
  has_many :reviews, through: :bookings

  def user?
    cars.empty?
  end

  def booker?
    bookings.any?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

	def check_owner_access
    unless current_user.owner?
		  redirect_to "/"
      flash[:notice] = "You don't have access"
    end
	end

	def check_user_access
    unless current_user.user?
		  redirect_to "/"
      flash[:notice] = "You don't have access"
    end
	end

	def check_booker_access
    unless current_user.booker?
		  redirect_to "/"
      flash[:notice] = "You don't have access"
    end
	end

	def owner?(item)
		item.user.id == current_user.id ? true : false
	end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	before_action :check_booker_access, only: [:edit, :update, :destroy]
	def new
		@booking = Booking.new
		@car = Car.find(params[:car_id])

		redirect_to car_path(@car) if @car.user == current_user
	end

	def index
		@bookings = Booking.all
	end

	def create
		@booking = Booking.new(booking_params)
		@car = Car.find(params[:car_id])
		@booking.car = @car
		@booking.user = current_user
		redirect_to car_path(@car) if @car.user == current_user
		if @booking.save!
			redirect_to car_bookings_path
		else
			render :new
		end
	end

	def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
	end

	private

		def booking_params
    params.require(:booking).permit(:start_date, :end_date, :car_id, :user_id)
		end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
	before_action :find_car, only: [:show, :edit, :update, :destroy]
	before_action :check_owner_access, only: [:update, :destroy]

	def index
    if params[:query].present?
      @cars = Car.search_by_manufacturer_and_model_and_year(params[:query])
    else
      @cars = Car.all
    end
	end

	def show
    @markers = [
      {
        lat: @car.latitude,
        lng: @car.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { car: @car }),
        image_url: @car.photos.any? ? @car.photos.first.service_url : 'https://kitt.lewagon.com/placeholder/cities/random'
      }
    ]
		@review = Review.new
	end

	def new
		@car = Car.new
	end

	def create
		@car = Car.new(car_params)
    @car.user = current_user
		if @car.save
			redirect_to car_path(@car)
		else
			render :new
    end
	end

	def edit
		@car = Car.find(params[:id])
		if !owner?(@car)
			redirect_to "/"
		end
	end

	def update
		@car = Car.find(params[:id])
    @car.update(car_params)
		redirect_to car_path(@car)
	end

	def destroy
		@car.destroy
		redirect_to cars_path
	end

	private

	def car_params
		params.require(:car).permit(:manufacturer, :model, :year, :address, :price, :rating, :description, photos: [])
	end

	def find_car
		@car = Car.find(params[:id])
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

def create
	@car = Booking.find(params[:booking_id]).car
	@review = Review.new(review_params)
	@review.car = @car
	if @review.save
		redirect_to car_path(@car)
	else
		render "cars/show"
	end
end

def destroy
	@review = Review.find(params[:id])
  @review.destroy
  redirect_to car_path(@review.car)
end

private

	def review_params
		params.require(:review).permit(:rating, :content)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>Your bookings</h1>

<div class="container">
  <ul class="list-group">
    <% current_user.bookings.each do |booking| %>
      <li class="list-group-item">
        <div class="card-product">
          <img <%= image_tag booking.car.photos.first.service_url, class: 'booking-car-photo' %>
          <div class="card-product-infos">
            <h2><%= booking.car.manufacturer %> <%= booking.car.model %> </h2>
            <p><%= booking.start_date %> to <%= booking.end_date %></p>
            <p><%= booking.car.address %> </p>
          </div>
          <%= link_to 'Cancel Booking', booking_path(booking), method: :delete %>
        </div>
        </li>
        <!-- <div class ="links"> -->
      <!-- <div class="btn btn-link"> -->
  <% end %>
</div>
<div class="links">
<button type="button" class="btn btn-link">
<%= link_to 'Back', cars_path %>
</button>
</div>
</ul>
</div>

app/views/bookings/new.html.erb
  <div class="image-new">
      <div class="image-new" style="background-image:  linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1564032236772-dfc27a12feda?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60')"></div>
      <!-- <img class="carousel-image d-block w-100" src="https://images.unsplash.com/photo-1527786356703-4b100091cd2c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2767&q=80" alt="First slide"> -->
    </div>
   <!-- <img class="carousel-image d-block w-100" src="https://images.unsplash.com/photo-1517342463979-7f018ddc30f7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=60" alt="Third slide"> -->

<h1 class="new"> Make a Booking</h1>
<h2 class="new2">The drive of your life</h2>
<div class="container d-flex justify-content-between">
  <div class="container-new">
    <%= simple_form_for [@car, @booking] do |f| %>
    <%= f.input :start_date, as: :date, html5: true %>
    <%= f.input :end_date, as: :date, html5: true %>
    <%= f.submit "Create Booking"%>
    <% end %>
    <br>
    <br>
</div>


<div class="booking-info">
  <h4>Terms & Conditions</h4>
<ul>
 <li>Same location for pick up and drop off</li>
 <li>£100 deposit</li>
 <li>Please take care of the car</li>
 <li>Contact the owner for any queries</li>
</ul>

  </div>
</div>

 <div class = "d-flex justify-content-center py-2">
    <button type="button" class="btn btn-ghost"><%= link_to 'Back to Listings', cars_path %></button>
  </div>

app/views/cars/_info_window.html.erb
<h3><%= car.model %></h3>
<p><%= car.address %></p>

app/views/cars/edit.html.erb
<h1> Edit Your Listing </h1>
    <div class="col-6 offset-3">
      <%= simple_form_for @car do |f| %>
        <%= f.error_notification %>
        <%= f.input :model %>
        <%= f.input :manufacturer %>
        <%= f.input :year %>
        <%= f.input :price %>
        <%= f.input :address %>
        <%= f.input :description, as: :text %>
        <%= f.submit "Edit Listing" %>
      <% end %>
    </div>

    <div class = "btn btn-link">
    <%= link_to "Back to car", car_path(@car) %>
    </div>

app/views/cars/index.html.erb
<h1> Browse All Cars </h1>

<div class="container">

 <div class="search-container">
  <%= form_tag cars_path, class: "search-form", method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a Car"
    %>
    <button type="submit" class="btn">
      <i class="fa fa-search"></i>
    </button>
   <% end %>
  </div>

  <div class="card-container">
    <div class="row">
      <% @cars.each do |car| %>
        <% next unless car.photos.attached? %>
        <div class="col-12 col-md-6 col-lg-4">
          <%= link_to car_path(car), class: 'card-link' do %>
            <div class="card">
              <%= cl_image_tag car.photos.first.key, class: "card-img" %>
                <div class="card-description">
                  <div class="card-title">
                    <p class="left-align"><%= car.manufacturer %>, <%= car.model %></p>
                    <p class="right-align"> <%= '☆' * (car.rating || 0) %></p>
                  </div>
                  <div class="card-information">
                    <%= car.description %>
                  </div>
                </div>
              <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="links">
  <% if params[:query].present? %>
    <button type="button" class="btn btn-link"> <%= link_to "Back to Cars", cars_path %></button>
  <% end %>
  <button type="button" class="btn btn-link"> <%= link_to "Add a new Listing", new_car_path(@car) %></button>
</div>

app/views/cars/new.html.erb
<div class="container-form body-white">
<h1> Add Your Listing </h1>
    <div class="col-6 offset-3 border border-car-form">
      <%= simple_form_for @car do |f| %>
        <%= f.error_notification %>
        <%= f.input :model %>
        <%= f.input :manufacturer %>
        <%= f.input :year %>
        <%= f.input :price %>
        <%= f.input :address %>
        <%= f.input :description, as: :text %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit "Create Listing" %>
      <% end %>
    </div>


    <div class = "links">
    <div class = "btn btn-link">
    <%= link_to "Back to listings", cars_path %>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <div class="overlay-fade">
      <%= image_tag @car.photos.first.service_url, class: 'first-car-photo' %>
        <div class="text" style="">
          <%= link_to 'Book Car', new_car_booking_path(@car) %>
        </div>
      </div>
    </div>
    <div class="col-6">
      <div class="row">
        <% @car.photos.drop(1).each do |photo| %>
          <div class="col-6">
            <%= image_tag photo.service_url, class: 'cars-photo' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>


  <div class="info-container">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="car-title"><%= @car.manufacturer %> <%= @car.model %></h1>
          <ul>
              <li class="lessli"><%= @car.description %></li>
              <li class="lessli"><%= @car.price %></li>
              <li class="lessli">Year: <%= @car.year %></li>
              <li class="lessli">Available to rent from:  <%= @car.address %></li>
              <li class="lessli"><%= '☆' * 5 %></li>
          </ul>
      </div>
    </div>
  </div>
</div>

<div class="links">
<button type="button" class="btn btn-link">
<%= link_to 'Back', cars_path %>
</button>
<button type="button" class="btn btn-link">
<%= link_to 'Book car', new_car_booking_path(@car) %>
</button>
</div>

</div>

<div class="d-flex" style="margin: 0 30px;">
  <div id="map"
       style="width: 50%;
       height: 600px;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <div class="reviews-container d-flex">
    <div class="reviews-list">
      <div style="width: 50vw; padding-left: 15px;">
        <div class ="review-header">
        <h3>Reviews</h3>
          <% if @car.reviews.empty? %>
            <p>Be the first to leave a review</p>
          <% else %>
        </div>
          <ul class="list-group">
            <% @car.reviews.each do |review| %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <span class="badge badge-primary badge-pill">
                  <% counter = 0 %>
                  <% 5.times do %>
                    <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
                    <% counter += 1 %>
                  <% end %>
                </span>
                <%= review.content %>
              </li>
            <% end %>
          </ul>
          <% end %>
      </div>
    </div>

    <div class="add-review">
    <% if @car.bookings.where(user: current_user).any? %>
      <%= render "reviews/new", car: @car, review: @review, booking: @car.bookings.where(user: current_user).last %>
    <% end %>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClassicCars</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Arvo&display=swap" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="min-height">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<!-- <p>Find me in app/views/pages/home.html.erb</p> -->

<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
<div class="index-title">
  <div>
    <h1 class="head">Hire a Vintage Car</h1>
    <h4 id="banner-description"></h4>
  </div>
</div>
  <ol class="carousel-indicators">
  <div>
    <button type="button" class="btn btn-ghost"><%= link_to 'Post Car', new_car_path %></button>
    <button type="button" class="btn btn-ghost"><%= link_to 'See Cars', cars_path %></button>
  </div>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="carousel-image d-block w-100" style="background-image:  linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1527786356703-4b100091cd2c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2767&q=80')"></div>
      <!-- <img class="carousel-image d-block w-100" src="https://images.unsplash.com/photo-1527786356703-4b100091cd2c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2767&q=80" alt="First slide"> -->
    </div>
    <div class="carousel-item">
      <div class="carousel-image d-block w-100" style="background-image:  linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1503242301233-4c5549f82b2d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1440&q=680')"></div>
      <!-- <img class="carousel-image d-block w-100" src="https://images.unsplash.com/photo-1503242301233-4c5549f82b2d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1440&q=680" alt="Third slide"> -->
    </div>
    <div class="carousel-item">
      <div class="carousel-image d-block w-100" style="background-image:  linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1521657286746-db1bebb1900a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=60')"></div>
      <!-- <img class="carousel-image d-block w-100" src="https://images.unsplash.com/photo-1521657286746-db1bebb1900a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=60" alt="Third slide"> -->
    </div>
    <div class="carousel-item">
      <div class="carousel-image d-block w-100" style="background-image:  linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1517342463979-7f018ddc30f7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=60')"></div>
      <!-- <img class="carousel-image d-block w-100" src="https://images.unsplash.com/photo-1517342463979-7f018ddc30f7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=60" alt="Third slide"> -->
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

    <section class="section-testimonials">
        <div class="row">
            <h3>Our customers can't live without us</h3>
        </div>
        <div class="row">
            <div class="col span-1-of-3">
                <blockquote> RoadKill Motor Works is just awesome! I dont own a car, so when I need to go somewhere fancy this website is a
                    life-saver. Now that I got used to it, I couldn't live without a renting a classic car!
                    <cite><img src="https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" alt="">(Alberto Duncan)</cite>
                </blockquote>
            </div>

            <div class="col span-1-of-3">
                <blockquote>Quick, easy and just great, many pick up locations next to my home. We have lots of
                     car rental services here in Lisbon,
                    but no one comes even close to RoadKill Motor Works. Me and my family are so in love!
                    <cite><img src="https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?cs=srgb&dl=women-s-white-and-black-button-up-collared-shirt-774909.jpg&fm=jpg" alt="">(Joana Silva)</cite>
                </blockquote>
            </div>

            <div class="col span-1-of-3">
                <blockquote>I was looking for a quick and easy car rental service in San Franciso. I tried a lot of
                    them and ended up with
                    RoadKill Motor Works. Best car rental service in the Area. Keep up the great work!
                    <cite><img src="https://images.pexels.com/photos/736716/pexels-photo-736716.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" alt="">(Milton Chapman)</cite>
                </blockquote>
            </div>
        </div>
    </section>

app/views/reviews/_new.html.erb
<h3>Add a review</h3>
<%= simple_form_for [booking, review] do |f| %>
<%= f.input :rating, collection: 0..5 %>
<%= f.input :content %>
<%= f.submit class: "btn btn-link"%>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      <!-- This footer is made with <i class="fas fa-heart"></i> by team Code for Change -->
    </div>
  </div>

app/views/shared/_navbar.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'classic.png' %> ROADKILL MOTOR WORKS
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Cars", cars_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Bookings", bookings_path, class: "nav-link" %>
        </li>
        <% if current_user.present? %>
          <li class="nav-item dropdown">
            <%= image_tag "https://i.ya-webdesign.com/images/avatar-icon-png-6.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>

            </div>
          </li>
        <% else %>
          <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>